FROM node:8

# Create app directory
WORKDIR /server

# Install typescript and nodemon
RUN yarn global add typescript

COPY . ./

RUN yarn install && \
    tsc

COPY ./ormconfig.js ./dist

CMD ["node", "dist/index.js"]




