version: '2'
services:
  todo-api-dev:
    build: .
    command: yarn run watch
    volumes: 
      - ./:/server
    ports:
      - "3000:3000"
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=my_database
  todo-api-prod: 
    build: 
     context: .
     dockerfile: Dockerfile.production
    ports:
      - "3001:3000"
    environment:
      - TYPEORM_CONNECTION=mongodb
      - TYPEORM_HOST=mongodb
      - TYPEORM_USERNAME=my_user
      - TYPEORM_PASSWORD=password123
      - TYPEORM_DATABASE=my_database
      - TYPEORM_ENTITIES=models/schema/*.js
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=true